config/routes.rb
Rails.application.routes.draw do

get 'sessions/new'

root                'application#index'
get    'results' => 'application#results'
get    'about'   => 'application#about'
get    'contact' => 'application#contact'
get    'help'    => 'application#help'
get    'signup'  => 'users#new'
get    'login'   => 'sessions#new'
post   'login'   => 'sessions#create'
delete 'logout'  => 'sessions#destroy'
resources :users
resources :newsletters
resources :flights

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    For any questions <a href="mailto:ardihamza@gmail.com">send an Email</a>.
  </small>
  <nav>
		<ul>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
			<li><%= link_to "Help", help_path %></li>
		</ul> 
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse" id="header">
	<div class="container">
		<%= link_to "Fluturama", root_path , id: "logo" %>
		<nav>
			<ul class="nav navbar-nav navbar-right"> 
				<% if logged_in? %>
					<li><%= link_to "Users", users_path %></li> 
					<li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
							<li><%= link_to "Profile", current_user %></li> 
							<li><%= link_to "Settings", edit_user_path(current_user) %></li>
							<li class="divider"></li>
							<li>
								<%= link_to "Log out", logout_path, method: "delete" %> 
							</li>
						</ul>
					</li> 
				<% else %>
					<li><%= link_to "Log In", login_path %></li> 
					<li><%= link_to "Sign Up", signup_path %></li> 
				<% end %>
			</ul> 
		</nav>
	</div>
</header>

app/views/layouts/_shim.html.erb
  <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Welcome to Fluturama</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	  <%= render "layouts/shim" %>

    <link rel="stylesheet" href='//fonts.googleapis.com/css?family=Dosis:300' rel='stylesheet' type='text/css'>
	  <link rel="stylesheet" type="text/css" media="screen" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" />
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link href="//cdn.rawgit.com/Eonasdan/bootstrap-datetimepicker/e8bddc60e73c1ec2475f827be36e1957af72e2ea/build/css/bootstrap-datetimepicker.css" rel="stylesheet">
    <link href="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/css/select2.min.css" rel="stylesheet" />

	  <script type="text/javascript" src="//code.jquery.com/jquery-2.1.1.min.js"></script>
		<script type="text/javascript" src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
		<script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment-with-locales.js"></script>
	  <script src="//cdn.rawgit.com/Eonasdan/bootstrap-datetimepicker/e8bddc60e73c1ec2475f827be36e1957af72e2ea/src/js/bootstrap-datetimepicker.js"></script>
		<script src="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/js/select2.min.js"></script>
	</head>

	<body>
		<%= render "layouts/header" %>
		<% flash.each do |message_type, message| %>
			<div class="alert alert-<%= message_type %>"><%= message %>
		</div> <% end %>
		<div class="container">
			<%= yield %>
			<%= render "layouts/footer" %>
			<%#= debug(params) if Rails.env.development? %>
		</div>
	</body>
</html>